### ISSUE TITLE
Check why README had incorrect Organizational Unit

### ISSUE THREAD

**Issue by kpeeples** [jbossdemocentral/dv-brms-integration-demo#8]
OU changed example to Demo

**Comment by kpeeples** [comment]
updated readme as brms repo change location from example to demo

**Comment by eschabell** [comment]
A small suggestion?

When making a code commit fix an issue, it is possible to link the code commit that fixes the issue by completing the commit message with "Fixes #{issue-number}".

On "git commit -m '{some-commit-message}. Fixes #8'; git push" it will auto publish your message to the issue, attach the code changes for tracking and close the issue.

**Comment by kpeeples** [comment]
Yes I know.
